-- PostgreSQL persistence used by cloudflare/domain-routes.ts. The existing
-- public.users table is created by 0001_users.sql and is intentionally reused.

CREATE TABLE IF NOT EXISTS public.role_capabilities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role TEXT NOT NULL,
  sector TEXT NOT NULL,
  capability TEXT NOT NULL,
  scope TEXT NOT NULL DEFAULT 'tenant',
  UNIQUE (role, sector, capability, scope)
);

CREATE TABLE IF NOT EXISTS public.sector_records (
  id TEXT PRIMARY KEY NOT NULL,
  sector TEXT NOT NULL,
  institution_id TEXT,
  school_id TEXT,
  owner_uid TEXT,
  record_type TEXT NOT NULL,
  record_json TEXT NOT NULL,
  created_by TEXT,
  is_deleted INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.payments (
  id TEXT PRIMARY KEY NOT NULL,
  institution_id TEXT,
  school_id TEXT,
  payer_id TEXT,
  amount INTEGER NOT NULL,
  currency TEXT NOT NULL DEFAULT 'UGX',
  status TEXT NOT NULL DEFAULT 'pending',
  provider TEXT,
  provider_reference TEXT,
  idempotency_key TEXT,
  metadata_json TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.audit (
  id TEXT PRIMARY KEY NOT NULL,
  institution_id TEXT,
  school_id TEXT,
  actor_id TEXT,
  action TEXT NOT NULL,
  resource_type TEXT,
  resource_id TEXT,
  metadata_json TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.school_admissions (
  id TEXT PRIMARY KEY NOT NULL,
  student_id TEXT NOT NULL DEFAULT '',
  full_name TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  education_level TEXT NOT NULL DEFAULT '',
  previous_experience TEXT NOT NULL DEFAULT '',
  institution_id TEXT,
  school_id TEXT,
  status TEXT NOT NULL DEFAULT 'submitted',
  record_json TEXT NOT NULL DEFAULT '{}',
  created_by TEXT NOT NULL DEFAULT '',
  is_deleted INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.marks (
  id TEXT PRIMARY KEY NOT NULL,
  admission_id TEXT NOT NULL DEFAULT '',
  provider_id TEXT NOT NULL DEFAULT '',
  student_id TEXT NOT NULL DEFAULT '',
  course_id TEXT NOT NULL DEFAULT '',
  course_title TEXT NOT NULL DEFAULT '',
  theory DOUBLE PRECISION NOT NULL DEFAULT 0,
  practical DOUBLE PRECISION NOT NULL DEFAULT 0,
  total DOUBLE PRECISION NOT NULL DEFAULT 0,
  grade TEXT NOT NULL DEFAULT '',
  passed INTEGER NOT NULL DEFAULT 0,
  entered_by TEXT NOT NULL DEFAULT '',
  institution_id TEXT,
  school_id TEXT,
  learner_id TEXT NOT NULL DEFAULT '',
  class_name TEXT NOT NULL DEFAULT '',
  subject TEXT NOT NULL DEFAULT '',
  score DOUBLE PRECISION,
  term TEXT NOT NULL DEFAULT '',
  maximum_score DOUBLE PRECISION,
  remarks TEXT NOT NULL DEFAULT '',
  record_json TEXT NOT NULL DEFAULT '{}',
  is_deleted INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.firestore_documents (
  document_path TEXT PRIMARY KEY NOT NULL,
  collection_path TEXT NOT NULL,
  firestore_name TEXT NOT NULL,
  data_json TEXT NOT NULL,
  update_time TEXT,
  create_time TEXT,
  imported_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.teacher_applications (
  id TEXT PRIMARY KEY NOT NULL,
  uid TEXT NOT NULL UNIQUE REFERENCES public.users(uid),
  application_type TEXT NOT NULL CHECK (application_type IN ('teacher_staff', 'teacher_independent')),
  organization_name TEXT,
  teaching_details TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  submitted_at TEXT NOT NULL,
  reviewed_at TEXT,
  reviewed_by TEXT,
  review_note TEXT,
  review_claim TEXT
);

CREATE TABLE IF NOT EXISTS public.parent_links (
  id TEXT PRIMARY KEY NOT NULL,
  institution_id TEXT,
  school_id TEXT,
  parent_uid TEXT NOT NULL REFERENCES public.users(uid),
  learner_id TEXT NOT NULL,
  relationship TEXT NOT NULL DEFAULT 'parent',
  active INTEGER NOT NULL DEFAULT 1,
  created_by TEXT NOT NULL,
  created_at TEXT NOT NULL,
  revoked_at TEXT
);

CREATE TABLE IF NOT EXISTS public.education_lessons (
  id TEXT PRIMARY KEY NOT NULL,
  institution_id TEXT,
  school_id TEXT,
  owner_uid TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  class_name TEXT NOT NULL,
  subject TEXT NOT NULL,
  youtube_url TEXT NOT NULL DEFAULT '',
  published INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.education_files (
  id TEXT PRIMARY KEY NOT NULL,
  lesson_id TEXT NOT NULL REFERENCES public.education_lessons(id) ON DELETE CASCADE,
  institution_id TEXT,
  school_id TEXT,
  object_key TEXT NOT NULL UNIQUE,
  filename TEXT NOT NULL,
  content_type TEXT NOT NULL DEFAULT 'application/pdf',
  size_bytes INTEGER NOT NULL,
  sha256 TEXT NOT NULL,
  created_by TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_role_capabilities_lookup
  ON public.role_capabilities (role, sector, scope);
CREATE INDEX IF NOT EXISTS idx_sector_records_tenant
  ON public.sector_records (institution_id, school_id);
CREATE INDEX IF NOT EXISTS idx_sector_records_owner
  ON public.sector_records (owner_uid, sector, record_type);
CREATE INDEX IF NOT EXISTS idx_payments_tenant
  ON public.payments (institution_id, school_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_idempotency
  ON public.payments (idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_audit_tenant_time
  ON public.audit (institution_id, school_id, created_at);
CREATE INDEX IF NOT EXISTS idx_school_admissions_scope
  ON public.school_admissions (institution_id, school_id, is_deleted, updated_at);
CREATE INDEX IF NOT EXISTS idx_school_marks_scope
  ON public.marks (institution_id, school_id, is_deleted, updated_at);
CREATE INDEX IF NOT EXISTS idx_firestore_documents_collection
  ON public.firestore_documents (collection_path);
CREATE INDEX IF NOT EXISTS idx_teacher_applications_status_submitted
  ON public.teacher_applications (status, submitted_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_parent_links_active_unique
  ON public.parent_links (parent_uid, learner_id) WHERE active=1;
CREATE INDEX IF NOT EXISTS idx_parent_links_parent
  ON public.parent_links (parent_uid, active);
CREATE INDEX IF NOT EXISTS idx_parent_links_learner
  ON public.parent_links (learner_id, active);
CREATE INDEX IF NOT EXISTS idx_education_lessons_scope
  ON public.education_lessons (institution_id, school_id, class_name, subject, published);
CREATE INDEX IF NOT EXISTS idx_education_files_lesson
  ON public.education_files (lesson_id);

INSERT INTO public.role_capabilities (role, sector, capability, scope) VALUES
  ('secretary', 'education', 'students.read', 'tenant'),
  ('secretary', 'education', 'students.manage', 'tenant'),
  ('secretary', 'education', 'attendance.manage', 'tenant'),
  ('secretary', 'education', 'admissions.manage', 'tenant'),
  ('secretary', 'education', 'reports.primary.read', 'tenant'),
  ('secretary', 'education', 'id_cards.manage', 'tenant'),
  ('secretary', 'education', 'communications.manage', 'tenant'),
  ('secretary', 'education', 'timetable.manage', 'tenant'),
  ('headteacher', 'education', 'students.read', 'tenant'),
  ('headteacher', 'education', 'students.secondary.manage', 'tenant'),
  ('headteacher', 'education', 'classes.manage', 'tenant'),
  ('headteacher', 'education', 'subjects.manage', 'tenant'),
  ('headteacher', 'education', 'marks.manage', 'tenant'),
  ('headteacher', 'education', 'grading.manage', 'tenant'),
  ('headteacher', 'education', 'teacher_assignments.manage', 'tenant'),
  ('headteacher', 'education', 'attendance.manage', 'tenant'),
  ('headteacher', 'education', 'reports.secondary.read', 'tenant'),
  ('headteacher', 'education', 'signatures.manage', 'tenant'),
  ('headteacher', 'education', 'communications.manage', 'tenant'),
  ('bursar', 'education', 'payments.manage', 'tenant'),
  ('bursar', 'education', 'fees.manage', 'tenant'),
  ('bursar', 'education', 'financial_reports.read', 'tenant'),
  ('bursar', 'education', 'reconciliation.manage', 'tenant'),
  ('bursar', 'education', 'statements.read', 'tenant'),
  ('bursar', 'education', 'statements.manage', 'tenant'),
  ('bursar', 'education', 'month_close.manage', 'tenant'),
  ('clinic_admin', 'clinic', 'records.read', 'tenant'),
  ('clinic_admin', 'clinic', 'records.manage', 'tenant'),
  ('doctor', 'clinic', 'records.read', 'tenant'),
  ('doctor', 'clinic', 'records.manage', 'tenant'),
  ('nurse', 'clinic', 'records.read', 'tenant'),
  ('nurse', 'clinic', 'records.manage', 'tenant'),
  ('receptionist', 'clinic', 'appointments.manage', 'tenant'),
  ('receptionist', 'clinic', 'patients.read', 'tenant'),
  ('pharmacist', 'clinic', 'pharmacy.manage', 'tenant'),
  ('pharmacist', 'clinic', 'patients.read', 'tenant'),
  ('patient', 'clinic', 'own.read', 'tenant'),
  ('patient', 'clinic', 'appointments.create', 'tenant'),
  ('farm_admin', 'farm', 'records.read', 'tenant'),
  ('farm_admin', 'farm', 'records.manage', 'tenant'),
  ('farm_director', 'farm', 'records.read', 'tenant'),
  ('farm_director', 'farm', 'records.manage', 'tenant'),
  ('farm_manager', 'farm', 'records.read', 'tenant'),
  ('farm_manager', 'farm', 'records.manage', 'tenant'),
  ('farm_worker', 'farm', 'records.own.read', 'tenant'),
  ('farm_worker', 'farm', 'records.own.manage', 'tenant'),
  ('mfi_admin', 'mfi', 'records.read', 'tenant'),
  ('mfi_admin', 'mfi', 'records.manage', 'tenant'),
  ('loan_officer', 'mfi', 'records.read', 'tenant'),
  ('loan_officer', 'mfi', 'loans.create', 'tenant'),
  ('loan_manager', 'mfi', 'records.read', 'tenant'),
  ('loan_manager', 'mfi', 'loans.approve', 'tenant'),
  ('loan_director', 'mfi', 'records.read', 'tenant'),
  ('loan_director', 'mfi', 'loans.approve', 'tenant'),
  ('borrower', 'mfi', 'records.own.read', 'tenant'),
  ('borrower', 'mfi', 'loans.create', 'tenant'),
  ('bursar', 'payments', 'payments.read', 'tenant'),
  ('bursar', 'payments', 'payments.create', 'tenant'),
  ('clinic_admin', 'payments', 'payments.read', 'tenant'),
  ('clinic_admin', 'payments', 'payments.create', 'tenant'),
  ('mfi_admin', 'payments', 'payments.read', 'tenant'),
  ('mfi_admin', 'payments', 'payments.create', 'tenant'),
  ('loan_officer', 'payments', 'payments.read', 'tenant'),
  ('loan_officer', 'payments', 'payments.create', 'tenant'),
  ('loan_manager', 'payments', 'payments.read', 'tenant'),
  ('loan_manager', 'payments', 'payments.create', 'tenant'),
  ('loan_director', 'payments', 'payments.read', 'tenant'),
  ('loan_director', 'payments', 'payments.create', 'tenant'),
  ('superadmin', '*', '*', 'tenant'),
  ('student', 'education', 'records.own.read', 'tenant'),
  ('learner', 'education', 'records.own.read', 'tenant'),
  ('teacher', 'education', 'teacher_assignments.read', 'tenant'),
  ('teacher', 'education', 'marks.manage', 'tenant'),
  ('teacher', 'education', 'attendance.manage', 'tenant'),
  ('student', 'education', 'lessons.read', 'tenant'),
  ('learner', 'education', 'lessons.read', 'tenant'),
  ('teacher', 'education', 'lessons.manage', 'tenant'),
  ('secretary', 'education', 'lessons.manage', 'tenant'),
  ('secretary', 'education', 'parent_links.manage', 'tenant'),
  ('headteacher', 'education', 'lessons.manage', 'tenant'),
  ('headteacher', 'education', 'parent_links.manage', 'tenant'),
  ('parent', 'education', 'lessons.read', 'tenant')
ON CONFLICT (role, sector, capability, scope) DO NOTHING;